<?php

namespace AppBundle\Repository;

/**
 * NurlCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurlCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
